### ISSUE TITLE
Extract historical versions to git 

### ISSUE THREAD

**Issue by larshp** [abapGit/git-historical-extract#1]
from https://github.com/larshp/abapGit/issues/3123

> For abap, the story typically does not start with git, there is a long history of development before git. I would like to be able to extract this history and have it in git as a starting point when moving to git.
> 
> This would enable stuff like git blame, and extracting historical metrics on the code.
> 
> I would imagine this as a separate abapGit tool, not part of the main codebase.

**Comment by ghost** [comment]
@larshp Hello, is there any unpublished progress in this project?

**Comment by larshp** [comment]
no

feel free to start it if you like, I have a few ideas/suggestions we can discuss it on [slack ](https://abapgit-slackinviter.herokuapp.com/)?

**Comment by larshp** [comment]
* objects will be placed according to current package structure, not historical
* deleted objects are not taken into account

**Comment by larshp** [comment]
closing, this is just a reminder, progress in https://github.com/abapGit/git-historical-extract/pull/2
